### ISSUE TITLE
Please add new line to end of SKTConversation.h & SKTUser.h

### ISSUE THREAD

**Issue by geoffspears** [radialpoint/SupportKit#40]
Our project uses the "Missing New Line At End Of File" warning available in XCode. In addition, some of our schemes treat warnings as errors. These two combined result in an inability to build some schemes when the SupportKit framework is included in our project due to the missing new line at the the end of the aforementioned headers.

**Comment by Dids** [comment]
There's only two ways this could be circumvented/fixed in SupportKit (that I see).
The first being the addition of new lines, which might be the easiest. The second would be to use pragmas and "-Wno-eof-newline" to ignore that specific warning.

Honestly though, treating missing new lines as errors instead of warnings just seems.. wrong. :P

**Comment by geoffspears** [comment]
Very true, we could ignore that particular warning. I figured I'd ask to see if the new lines could be added as that seemed like the path of least resistance. :)

**Comment by mspensieri** [comment]
Should be fixed in v2.6.1 :)
