### ISSUE TITLE
SKTConversationDelegate Issue!

### ISSUE THREAD

**Issue by EMidee66** [radialpoint/SupportKit#45]
SKTConversationDelegate methods are not being called.

**Comment by mspensieri** [comment]
Uh oh! @EMidee66 Could you paste in your init code where you set up your `SKTConversationDelegate` please? My initial hunch is that you are not maintaining an external reference to your delegate object; SupportKit only maintains a weak reference, so if you create an object and do not retain it yourself, it will be deallocated.

Another thing to be aware of is that you can only set your delegate after the call to `initWithSettings:`, otherwise the `SKTConversation` object will be `nil`.

Can you please verify that you're handling both these cases correctly, then let me know? Thanks!

**Comment by EMidee66** [comment]
Thank you @mspensieri for your response. 
I am a bit confused. So should I create an nsobject that conforms to SKTConversationDelegate. What I did was just add it to a ViewController and then i called the methods.
So after I call initWithSettings what steps should I follow?

**Comment by mspensieri** [comment]
@EMidee66 You can either create a separate `NSObject` subclass that implements the `SKTConversationDelegate` protocol, or you can add the functionality to one of your existing classes. If you'd like to set a specific view controller as the delegate, then make sure that this view controller is never deallocated, otherwise you will no longer receive the delegate messages.

The easiest way is probably to use your `UIApplicationDelegate` as the conversation delegate, and register it in `application:didFinishLaunchingWithOptions:` after your call to `initWithSettings:`

```
@interface MyAppDelegate : UIResponder <UIApplicationDelegate, SKTConversationDelegate>
@end

@implementation MyAppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.window.rootViewController = [[UIViewController alloc] init];
    [self.window makeKeyAndVisible];

    [SupportKit initWithSettings:[SKTSettings settingsWithAppToken:@"......"]];
    [SupportKit conversation].delegate = self;
    
    return YES;
}

@end
```

**Comment by EMidee66** [comment]
It worked. Thank you very much :)
Have a great day!

**Comment by mspensieri** [comment]
Great!
