### ISSUE TITLE
Compilation issue using Cocoapod 2.10.2

### ISSUE THREAD

**Issue by gemmakbarlow** [radialpoint/SupportKit#54]
Hey guys,

Receiving the following error when compiling using the latest Cocoapod - thought you'd like a heads up.

<code>
ld: framework not found ModelIO for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
</code>

Occurs when compiling against iOS 8 SDK, Xcode Version 6.4 (6E35b)

<code>-</code>G

**Comment by mspensieri** [comment]
@gemmakbarlow Thanks for the report, but this is intended. As of [v2.10.1](https://github.com/radialpoint/SupportKit/releases/tag/v2.10.1), we now require Xcode7 to compile due to the addition of bitcode support.

If you don't yet want to upgrade to Xcode7, you can pin your CocoaPod to use v2.10.0

**Comment by gemmakbarlow** [comment]
Got it - thanks. Might be worth a note in the Release notes.

https://github.com/radialpoint/SupportKit/releases

**Comment by gemmakbarlow** [comment]
*facepalm* - sorry - I see the note now :)

**Comment by mspensieri** [comment]
:smile:

**Comment by fatuhoku** [comment]
@mspensieri Thanks for the note — this was really baffling me. I would really appreciate it if the SupportKit SDK versioning bump up the major number rather than a patch version.

This is because [SemVer](http://semver.org/) mandates that you should bump the major version number for anything that will break backwards compatibility. If I had seen that SK upgraded from 2.x to 3.x I would have saved a lot of time trying to figure out what caused `ModelIO` to appear even though it was not mentioned anywhere in my project!
